# Generated by Django 4.2.11 on 2024-05-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('bibliotheque', '0003_alter_books_categories'),
        ('users', '0002_rename_customuser_bibliothequaires'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bibliothequaires',
            new_name='CustomUser',
        ),
    ]
