# Generated by Django 4.2.11 on 2024-05-05 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bibliotheque', '0003_alter_books_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Livres',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='livres',
            old_name='name',
            new_name='nom',
        ),
    ]
